import { createActionTypes } from '../util/actionsUtil';

export const WORKSPACES = createActionTypes('WORKSPACES');
export const WORKSPACE = createActionTypes('WORKSPACE');
export const CREATE_WORKSPACE = createActionTypes('CREATE_WORKSPACE');
export const UPDATE_WORKSPACE = createActionTypes('UPDATE_WORKSPACE');
export const DELETE_WORKSPACE = createActionTypes('DELETE_WORKSPACE');
export const CHANNELS = createActionTypes('CHANNELS');
export const CHANNEL = createActionTypes('CHANNEL');
export const CREATE_CHANNEL = createActionTypes('CREATE_CHANNEL');
export const UPDATE_CHANNEL = createActionTypes('UPDATE_CHANNEL');
export const DELETE_CHANNEL = createActionTypes('DELETE_CHANNEL');
export const MESSAGE = createActionTypes('MESSAGE');
export const CREATE_MESSAGE = createActionTypes('CREATE_MESSAGE');
export const UPDATE_MESSAGE = createActionTypes('UPDATE_MESSAGE');
export const DELETE_MESSAGE = createActionTypes('DELETE_MESSAGE');
export const CREATE_WORKSPACE_SUB = createActionTypes('CREATE_WORKSPACE_SUB');
export const DELETE_WORKSPACE_SUB = createActionTypes('DELETE_WORKSPACE_SUB');
export const CREATE_CHANNEL_SUB = createActionTypes('CREATE_CHANNEL_SUB');
export const DELETE_CHANNEL_SUB = createActionTypes('DELETE_CHANNEL_SUB');
export const FAVORITES = createActionTypes('FAVORITES');
export const CREATE_FAVORITE = createActionTypes('CREATE_FAVORITE');
export const DELETE_FAVORITE = createActionTypes('DELETE_FAVORITE');
export const CREATE_REACTION = createActionTypes('CREATE_REACTION');
export const DELETE_REACTION = createActionTypes('DELETE_REACTION');
